export const ADICIONAR_POST = "ADICIONAR_POST";
export const REMOVER_POST = "REMOVER_POST";
export const FETCH_POST_SUCESSO = "FETCH_POST_SUCESSO";
export const FETCH_POST_INICIADO = "FETCH_POST_INICIADO";